var tree = [["Icecave",,"",
                [["Duct","Icecave\/Duct.html","",
                [["Detail","Icecave\/Duct\/Detail.html","",
                [["Exception","Icecave\/Duct\/Detail\/Exception.html","",
                [["LexerException","Icecave\/Duct\/Detail\/Exception\/LexerException.html"," < RuntimeException",
                [        ]],["ParserException","Icecave\/Duct\/Detail\/Exception\/ParserException.html"," < RuntimeException",
                [        ]]        ]],["Lexer","Icecave\/Duct\/Detail\/Lexer.html"," < EventEmitter",
                [        ]],["LexerState","Icecave\/Duct\/Detail\/LexerState.html"," < Enumeration",
                [        ]],["ParserState","Icecave\/Duct\/Detail\/ParserState.html"," < Enumeration",
                [        ]],["Token","Icecave\/Duct\/Detail\/Token.html","",
                [        ]],["TokenStreamParser","Icecave\/Duct\/Detail\/TokenStreamParser.html"," < EventEmitter",
                [        ]],["TokenType","Icecave\/Duct\/Detail\/TokenType.html"," < Enumeration",
                [        ]]        ]],["Exception","Icecave\/Duct\/Exception.html","",
                [["SyntaxExceptionInterface","Icecave\/Duct\/Exception\/SyntaxExceptionInterface.html","",
                [        ]]        ]],["AbstractParser","Icecave\/Duct\/AbstractParser.html","",
                [        ]],["EventedParser","Icecave\/Duct\/EventedParser.html"," < AbstractParser",
                [        ]],["PackageInfo","Icecave\/Duct\/PackageInfo.html","",
                [        ]],["Parser","Icecave\/Duct\/Parser.html"," < AbstractParser",
                [        ]]        ]]        ]]        ]

